export const apiPrefix = "api";
export const authPrefix = "auth";
export const todoRoute = "todos";
export const userRoute = "users";
export const teamRoute = "teams";
export const teamMemberRoute = "team-members";
export const loginRoute = "login";
export const registerRoute = "register";
export const logoutRoute = "logout";
export const checkRoute = "check";
export const refreshRoute = "refresh";
export const ACCESS_TOKEN_EXP = 60 * 60; // 1 hour
export const REFRESH_TOKEN_EXP = 7 * 86400; // 7 days
